---
os: linux
dist: bionic
language: shell
python:
  - "3.8"


# branches:
#   only:
#   - master

jobs:
  fast_finish: true
  include:
  - name: "ansible-2.10"
    env:
      - ANSIBLE_VERSION="2.10.*"
      - MOLECULE_VERSION="3.*"
      - TAG="ansible-2.10"
  - name: "ansible-2.9"
    env:
      - ANSIBLE_VERSION="2.9.*"
      - MOLECULE_VERSION="3.*"
      - TAG="ansible-2.9"

services:
  - docker

before_install:
  - |
    docker build -t leandelivery/docker-ansible-ci:$TAG \
    --build-arg ANSIBLE_VERSION \
    --build-arg MOLECULE_VERSION \
    .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
